[RSI]
n = [10, 20, 1]
low = [0, .5, .1]
high = [.5,1,.1]
persistence = [1,5,1]

[BBANDS]
n = [15,25,1]
nbdevdn = [0.5, 2.5, 2]
nbdevup = [0.5, 2.5, .2]

[MACD]
n_fast = [10,16,1]
n_slow = [23,30,1]
down = [0,4,.2]
up = [0,4,.2]
persistence = [1,5,1]
