[MISC]
opt = 1
tries = 100

[RSI]
n = [10, 20, 1]
low = [0.0, 0.5, 0.1]
high = [0.5,1.0,0.1]
persistence = [1,6,1]

[CCI]
n = [10,20,1]
up = [0.3, 3.0, 0.3]
down = [0.3, 3.0, 0.3]
persistence = [1,6,1]

[MACD]
n_fast = [10,16,1]
n_slow = [23,30,1]
down = [0.0,4.0,0.2]
up = [0.0,4.0,0.2]
persistence = [1,5,1]
